Transpose and Concatenation

In [2]:
import numpy as np 
#For single dim, axis= 0 , no 1

a = np.array([1,2,3,4])
b = np.array([7,8,9,10])
 
res1 = np.transpose((a,b))

print(res1)
res = np.concatenate((a,b) , axis = 0)

print(res)



[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]]
[ 1  2  3  4  7  8  9 10]


In [ ]:
c = np.array([[1,2] , [3,4]])
d = np.array([[6,7] , [8,2]])

print(c)
print(d)

print("Moduling the two variables:")
print(c%d)
print("Power operation.")
print(c**d)

[[1 2]
 [3 4]]
[[6 7]
 [8 2]]
Moduling the two variables:
[[1 2]
 [3 0]]
[[   1  128]
 [6561   16]]
