Generating sequence of the dates


In [1]:
import pandas as pd
import numpy as np
df= pd.date_range('28-05-2026',periods=6)
print(df)

DatetimeIndex(['2026-05-28', '2026-05-29', '2026-05-30', '2026-05-31',
               '2026-06-01', '2026-06-02'],
              dtype='datetime64[us]', freq='D')


In [17]:
df= pd.read_csv('tips.csv')
# print(df.to_string())

print(pd.options.display.max_rows)

#it diplays all the rows of the csv file
# print(df.to_string())

#custom rows
pd.options.display.max_rows=200
print(df)

200
     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]


In [ ]:
res = df[df['total_bill']>20]
res

,total_bill,tip,sex,smoker,day,time,size
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
5,25.29,4.71,Male,No,Sun,Dinner,4
7,26.88,3.12,Male,No,Sun,Dinner,4
11,35.26,5.00,Female,No,Sun,Dinner,4
15,21.58,3.92,Male,No,Sun,Dinner,2
19,20.65,3.35,Male,No,Sat,Dinner,3
21,20.29,2.75,Female,No,Sat,Dinner,2
23,39.42,7.58,Male,No,Sat,Dinner,4


In [20]:
#Value_count

res1 = df['day'].value_counts()
print(res1)

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64


In [21]:
df= pd.read_json('tips.json')
df

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3
240,27.18,2.00,Female,Yes,Sat,Dinner,2
241,22.67,2.00,Male,Yes,Sat,Dinner,2
242,17.82,1.75,Male,No,Sat,Dinner,2


In [29]:
#Removing the empty rows
df= pd.read_csv('tips.csv')
# print(df)


#Deleting the empty rows
# df.dropna(inplace=True)
# print(df)

#Filling empty cells

#replace by the value
# df.fillna({ 'total_bill': 0 ,'time':'-'}, inplace=True)


#Repalce by the mean, mode , median
x = df['total_bill'].mean()
df.fillna({'total_bill':x},inplace = True)
print(df)

     total_bill   tip     sex smoker   day    time  size
0      19.83166  1.01  Female     No   Sun  Dinner     2
1      19.83166  1.66    Male     No   Sun  Dinner     3
2      19.83166  3.50    Male     No   Sun  Dinner     3
3      23.68000  3.31    Male     No   Sun  Dinner     2
4      24.59000  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239    29.03000  5.92    Male     No   Sat  Dinner     3
240    27.18000  2.00  Female    Yes   Sat  Dinner     2
241    22.67000  2.00    Male    Yes   Sat  Dinner     2
242    17.82000  1.75    Male     No   Sat  Dinner     2
243    18.78000  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]


Numpy..........

In [36]:
import numpy as np 
print(np.__version__)

a= np.array([1,2,3,4,5])
print(a,type(a))
print(a.dtype)

2.4.6
[1 2 3 4 5] <class 'numpy.ndarray'>
int64


In [37]:
#2 [] brackets then 2- Dimensional array , if 7 [] then 7- dimensional aray

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [41]:
c = np.zeros(6)
print(c)

[0. 0. 0. 0. 0. 0.]


In [42]:
#@-D array.....
d= np.ones((4,2))
d

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
#3-d
d= np.ones((4,2,3))
d

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])