In [2]:
import numpy as np

a = np.random.rand(10)
print(a)
b = np.random.rand(2,3)
print(b)

[0.19568374 0.06107501 0.68230179 0.37916169 0.70709806 0.95544628
 0.13050832 0.69698487 0.0977802  0.31931141]
[[0.04633556 0.60580795 0.33976777]
 [0.22427794 0.20869202 0.87546058]]


In [4]:
empty = np.empty((2,3))
print(empty)

[[0.04633556 0.60580795 0.33976777]
 [0.22427794 0.20869202 0.87546058]]


In [5]:
full = np.full((2,3),5)
print(full)

[[5 5 5]
 [5 5 5]]


In [ ]:
#Accesing the arrays....
b = np.array([1,2,3,4])
print(b[2])

#MAthematical operation...
print(b[2]+b[1])

#2 D

c = np.array([[1,2,3],
              [4,5,6]])
print(c[1,2])

#3D
arr = np.array([[[1, 2, 3],
                  [4, 5, 6]],

                    [[7, 8, 9],
                      [10, 11, 12]]])
print(arr[1,1,2])   #12

print(arr[1,1,-2])    #11(last second element.)

3
5
6
12
11


NumPy Array Slicing

In [16]:
b = np.array([1,2,3,4])
print(b[0:2])

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])        #5,6

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])
print(arr[1,1:4])
print(arr[0:2 , 2])

print(arr[0:2 , 1:4])

[1 2]
[5 6]
[2 4]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


# 3D Arrays

In [ ]:
a = np.array([
    [[1,2],
     [3,4]],
     [[4,5],
      [6,7]]
      ])

print(a)
print('Array Shape',a.shape)  #(2(blocks),2(rows),2(columns))

print(a[1,1,0])    #6

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]
Array Shape (2, 2, 2)
6


In [21]:
#Another example
arr = np.zeros([3,2,4])
print(arr ,"\nArray shape:", arr.shape)

full = np.full([4,3,5] , 3)
print(full)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]] 
Array shape: (3, 2, 4)
[[[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]


In [ ]:
#copy = changes the a but not x, in case of the ,view = both x and a are changed ..............
a = np.array([1,2,3,4])
x = a.copy()          
a[3] = 100
print(a)
print(x)

[  1   2   3 100]
[1 2 3 4]


In [25]:
# base attribute , we can check that our data owns it own data or not .
a = np.array([1,2,3,4])
x = a.copy() 
y = a.view()

print(x.base)
print(y.base)

None
[1 2 3 4]


In [ ]:
#Reshaping the array        (returns a tuple )
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]
