Swapping the values

In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
print("Original:",a)
a[1],a[4] = a[4],a[1]
print("Swapped:",a)

Original: [1 2 3 4 5]
Swapped: [1 5 3 4 2]


In [20]:
#Row swapping....
# b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# print(b)

# b[[0,2] ,: ] = b[[2,0] ,:]
# print("Swapped rows:\n",b)
# b[[0,1,2],: ] = b[[2,0,1], :]     #Comma between the rows and column is must .
# print("Swapped rows:\n",b)
# #Column swapping.....
# a8 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# print("Column swapping:\n",a8)
# a8[ :,[0,1]] =  a8[ :,[1,0]]
# print("Swapped column:\n",a8)

a9 = np.arange(1,19).reshape(3,3,2)
print("3D array:\n",a9)

# a9[[1,2] ,: ,:] = a9[[2,1],:,:]
# print("Swapped set 3D array:\n",a9)
# #arr[set,row,column] = arr[set,row,column]

# print("Swapped:\n")
# a9[[1],[1,2],:] = a9[[1],[2,1],:]
# print(a9)

print(" ")
a9[[0,1],[1],[0]] = a9[[1,0],[1],[0]]
print(a9)


3D array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
 
[[[ 1  2]
  [ 9  4]
  [ 5  6]]

 [[ 7  8]
  [ 3 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
