1) Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]]

In [3]:
import pandas as pd
df = pd.read_csv('leads.csv')
print(df)



    Index       Account Id         Lead Owner First Name  Last Name  \
0       1  0970F99ED4a2CE4                NaN     Victor    Cochran   
1       2  e9AABddbCA4AFee                NaN    Maureen    Fuentes   
2       3  99CF54fE56dDc5e                NaN      Ralph    Murillo   
3       4  5B8C661A897ACE3      Dana Mcdonald    Richard     Obrien   
4       5  2C7aEb5e8F432Ab        Sharon Cruz      Terri      Perry   
..    ...              ...                ...        ...        ...   
95     96  879AA6f76aCcEeF         Mary Terry      Erica   Garrison   
96     97  f8EBCd52d798D8f     Vincent Mcneil   Fernando  Dickerson   
97     98  bcCE5c7bEbdFfB2         Colin Choi     Sheila       Dyer   
98     99  6cC0Dc8e4410B7E          Tony Beck     Cassie     Conrad   
99    100  DCabaF160FbDda8  Dillon Stephenson  Charlotte   Browning   

                    Company                Phone 1               Phone 2  \
0   Grimes, Madden and Huff        +1-532-344-1362            275473337

In [5]:
#Replace NaN with zero.
res = df.fillna('0', inplace=True)
print(df)

    Index       Account Id         Lead Owner First Name  Last Name  \
0       1  0970F99ED4a2CE4                  0     Victor    Cochran   
1       2  e9AABddbCA4AFee                  0    Maureen    Fuentes   
2       3  99CF54fE56dDc5e                  0      Ralph    Murillo   
3       4  5B8C661A897ACE3      Dana Mcdonald    Richard     Obrien   
4       5  2C7aEb5e8F432Ab        Sharon Cruz      Terri      Perry   
..    ...              ...                ...        ...        ...   
95     96  879AA6f76aCcEeF         Mary Terry      Erica   Garrison   
96     97  f8EBCd52d798D8f     Vincent Mcneil   Fernando  Dickerson   
97     98  bcCE5c7bEbdFfB2         Colin Choi     Sheila       Dyer   
98     99  6cC0Dc8e4410B7E          Tony Beck     Cassie     Conrad   
99    100  DCabaF160FbDda8  Dillon Stephenson  Charlotte   Browning   

                    Company                Phone 1               Phone 2  \
0   Grimes, Madden and Huff        +1-532-344-1362            275473337

In [ ]:
#Now with the help of the given data.....

import numpy as np 

arr = np.array([[6, -8, 73, -110],[np.nan, -8, 0, 94]])
print("Original Array!!")
print(arr)

#Numpy as no attribute fillna , so we use the nan_to_num function by passing the arr and the nan = value to be replaced 
arr = np.nan_to_num(arr, nan=0)
arr

Original Array!!
[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]


array([[   6.,   -8.,   73., -110.],
       [   0.,   -8.,    0.,   94.]])

Interchange rows and columns (Transpose)

In [9]:
arr = arr.T
print("\nAfter Interchanging Rows and Columns:")
print(arr)


After Interchanging Rows and Columns:
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


#  2) Move axes of 3D array to new positions

np.moveaxis(array, source, destination)

In [ ]:
# Create 3D array
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print("Original Array:")
print(arr)

# Move axes
#Move axis 0 to axis 2
new_arr = np.moveaxis(arr, 0, 2)

print("\nAfter Moving Axis:")
print(new_arr)

Original Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

After Moving Axis:
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


3) Replace NaN values with average of columns 

In [11]:
# Create array
arr = np.array([[10, 20, np.nan],
                [40, np.nan, 60],
                [70, 80, 90]])
print("Original:")
print(arr)

Original:
[[10. 20. nan]
 [40. nan 60.]
 [70. 80. 90.]]


np.mean() propagates NaN values, while np.nanmean() ignores them during average calculation.

In [17]:

# Column mean ignoring NaN
#Axis = 0 , column wise mean 
mean = np.nanmean(arr, axis=0)

# Replace NaN
arr[np.isnan(arr)] = mean[np.where(np.isnan(arr))[1]]
# 1= give SECOND array , 0 = give FIRST array
print(arr)

[[10. 20. 75.]
 [40. 50. 60.]
 [70. 80. 90.]]


4) Replace negative value with zero in numpy array using replace

there is NO replace() function used.

This method is called:

Boolean Indexing / Conditional Replacement

Then Why Did Your Question Say “using replace”?

Because NumPy does not have a direct .replace() method like Pandas.

In NumPy, replacement is usually done using:

arr[condition] = value

BEST PRACTICE is this

In [21]:
arr = np.array([10,-5,20,-8,30])

arr[arr < 0] = 0

print(arr)

[10  0 20  0 30]


np.where(condition, true_value, false_value)

if condition is True → use true_value
else → use false_value

In [ ]:
#OR(ALTERNATIVE)
arr = np.array([10,-5,20,-8,30])

arr = np.where(arr < 0, 0, arr)

print(arr)

[10  0 20  0 30]


In Pandas

There is an actual replace() function.

In [19]:
import pandas as pd

s = pd.Series([10,-5,20,-8])

s.replace(-5,0)

0    10
1     0
2    20
3    -8
dtype: int64