In [4]:
import numpy as np

In [ ]:
#1) Create numpy array and perform following operation > Convert 1D array to 2D
a = np.array([1,2,3,4,5,6])
print("Original",a)
a2d = a.reshape(2,3)
print("Reshaped_2D:\n",a2d)

Original [1 2 3 4 5 6]
Reshaped_2D:
 [[1 2 3]
 [4 5 6]]


In [4]:
#Print Array Attributes(Like shape, dimenssion, data type, itemsize)

print(a2d.shape) #shape
print(a2d.ndim)
print(a2d.dtype)
print(a2d.itemsize)

(2, 3)
2
int64
8


In [6]:
#Create a 3×3 NumPy array of all 9
a2 = np.full((3,3),9)
print(a2)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [7]:
# Create a 1D array of 10 evenly spaced values between 25 and 125 

a3 = np.linspace(25,125,10)
print(a3)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [10]:
l = [1,2,3,4,5,6]
a4 = np.array(l)
print(a4)

[1 2 3 4 5 6]


In [11]:
#Reverse a 1D NumPy array
a5 = a4[ : :-1]
print(a5)

[6 5 4 3 2 1]


In [5]:
#Create a 4×4×3 array and extract value at its second set, first row and last column 

a6 = np.random.randint(1,100,(4,4,3))
print(a6)

print(a6[1,0,2])

[[[50 11 26]
  [26 44  2]
  [79 94 96]
  [91 36  6]]

 [[ 5 58 59]
  [30  2 11]
  [ 1 67 75]
  [35 44 34]]

 [[60 39 41]
  [76  3 17]
  [13 15 20]
  [33 13  2]]

 [[73 15 16]
  [13  7 33]
  [72 81 11]
  [ 9 49 28]]]
59


In [16]:
#Create a 4×4 and Extract Odd Rows and Even Columns 
a7 = np.arange(1,17).reshape(4,4)
print(a7)
print(a7[::2, 1::2])
print("\nOdd Rows and Even Columns:\n",a7)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 2  4]
 [10 12]]

Odd Rows and Even Columns:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [7]:
# Slice the first two rows and first two columns of the second set from a 4×4×3 array
print(a6)

sliced = a6[1, :2, :2]
print(sliced)

[[[50 11 26]
  [26 44  2]
  [79 94 96]
  [91 36  6]]

 [[ 5 58 59]
  [30  2 11]
  [ 1 67 75]
  [35 44 34]]

 [[60 39 41]
  [76  3 17]
  [13 15 20]
  [33 13  2]]

 [[73 15 16]
  [13  7 33]
  [72 81 11]
  [ 9 49 28]]]
[[ 5 58]
 [30  2]]


In [1]:
#Replace all odd numbers in a NumPy array with -1 by itterating using for loop [[23, 56, 78, 93], [71, 82,13, 24]] 

import numpy as np
a8 = np.array([[23, 56, 78, 93], 
                [71, 82,13, 24]])

# for i in np.nditer(a8):
#     print(i);

for i in range(a8.shape[0]):
    for j in range(a8.shape[1]):
        if a8[i][j] %2 != 0:
            a8[i][j] = -1

print("Modofied:\n",a8)

Modofied:
 [[-1 56 78 -1]
 [-1 82 -1 24]]


In [2]:
#Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4] 

a9 = np.array([1, 0, 2, 0, 3, 0, 4])
indices = np.nonzero(a9)
print(indices)

(array([0, 2, 4, 6]),)


In [3]:
#Perform arithmetic operations on two NumPy arrays element-wise Add two NumPy arrays element by element. Multiply two NumPy arrays element by element
a10 = np.array([1,2,3,4])
a11 = np.array([1,2,3,4])
add = a10 +a11
print("Addition\n",add)
mul = a10 * a11
print("Multiplication:\n",mul)

Addition
 [2 4 6 8]
Multiplication:
 [ 1  4  9 16]


In [4]:
#Write a code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] arr2 = [10,40,37]

a12 = np.array([15,20,25])
a13 = np.array([10,40,37])

dot_Product = np.dot(a12,a13)
print("Dot Product of two numpy arrays:",dot_Product)

Dot Product of two numpy arrays: 1875
